# Generated by Django 5.1.6 on 2025-02-22 13:14

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Embeddings', pgvector.django.vector.VectorField(dimensions=768)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('Embeddings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.embeddings')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompetence',
            fields=[
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.userauth')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.embeddings')),
            ],
        ),
    ]
