# Generated by Django 5.1.6 on 2025-02-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Embeddings',
            new_name='Embedding',
        ),
        migrations.RenameField(
            model_name='competence',
            old_name='Embeddings_id',
            new_name='embedding_id',
        ),
        migrations.RenameField(
            model_name='embedding',
            old_name='Embeddings',
            new_name='embedding',
        ),
    ]
