services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - "ollama_models:/root/.ollama"
    post_start:
      - command: ollama pull mxbai-embed-large
    networks:
      - ollama-docker
      
  pgdb:
    container_name: postgresdb
    image: ankane/pgvector
    restart: unless-stopped
    volumes: 
      - "pgsql_db:/var/lib/postgresql/data"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"
    env_file: ./.env
    networks:
      - ollama-docker

  competiapp:
    container_name: competiapp
    image: Sprinter05/competiapp:v1
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    env_file: ./.env
    networks:
      - ollama-docker

volumes:
  ollama_models:
  pgsql_db:

networks:
  ollama-docker:
    external: false
