# Compose a postgres database together with the extension pgvector
services:
  ollama:
    container_name: embedder
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ollama-local:/root/.ollama
  pgdb:
    hostname: db
    container_name: pgdb
    image: ankane/pgvector
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    env_file: ./.env
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  ollama-local:
  open-webui-local:
